### PR TITLE
Raise UnicodeEncodeError in case encode iso-8859-1

### PR DESCRIPTION
**Pull request by nan-tic-dev**
#165203

### CODE REVIEW

**Review by albertca — COMMENTED** [review]
I think it is better to use `errors='ignore'` in encode:

https://docs.python.org/3/library/stdtypes.html#str.encode

There are characters that will never possible to convert to iso-8859-1 and we must not limit the encodings of the records in the database to the most restricting characters.

**Comment by bernatnan** [comment]
The problem is that, normally the bad char is in the party name, and ignore it, could produce an incorrect name and the AEAT will rise an error. With this will avoid the AEAT error, before it will produce and advise the user.

**Comment by albertca** [comment]
> The problem is that, normally the bad char is in the party name, and ignore it, could produce an incorrect name and the AEAT will rise an error. With this will avoid the AEAT error, before it will produce and advise the user.

errors='ignore' does not create an invalid string but simply does not convert the character.

See the link.

**Comment by bernatnan** [comment]
I've read the information from the link, an as I understand from "Ignore the malformed data and continue without further notice", this will produce or a bad name or a file not completely encoded with iso-8859-1, in both cases the AEAT will not accept the file.

**Comment by albertca** [comment]
> I've read the information from the link, an as I understand from "Ignore the malformed data and continue without further notice", this will produce or a bad name or a file not completely encoded with iso-8859-1, in both cases the AEAT will not accept the file.

It will be correct. Just try it:

```
>>> a = '|❤|'
>>> a.encode('iso-8859-1')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 1-2: ordinal not in range(256)
>>> a.encode('iso-8859-1', errors='replace')
b'|??|'
>>> a.encode('iso-8859-1', errors='ignore')
b'||'
```

**Comment by raimonesteve** [comment]
> ```
> >>> a.encode('iso-8859-1', errors='ignore')
> b'||'
> ```

Done 1405d91e513a71e78b16d94b5c8386310ba8251d

**Pull request closed without merging**
